### PR TITLE
Update protractor_install command for protractor 0.14.0

### PR DESCRIPTION
**Pull request by sublimino**
https://github.com/angular/protractor/blob/master/CHANGELOG.md

### CODE REVIEW

**Comment by clkao** [comment]
perhaps also update package.json for `"protractor": "~0.14.0"` ?

**Comment by sublimino** [comment]
@clkao updated

**Comment by caspian311** [comment]
Can we get this merged in? Master as is does not work and the proposed PR seems to work.

**Comment by inklesspen** [comment]
You'll also need to update the default paths in `test/protractor.conf.js`. (or at least I had to)

``` diff
diff --git a/test/protractor.conf.js b/test/protractor.conf.js
index e955d5a..020fba8 100644
--- a/test/protractor.conf.js
+++ b/test/protractor.conf.js
@@ -11,7 +11,7 @@ exports.config = {
   // 3. sauceUser/sauceKey - to use remote Selenium servers via SauceLabs.

   // The location of the selenium standalone server .jar file.
-  seleniumServerJar: './selenium/selenium-server-standalone-2.37.0.jar',
+  seleniumServerJar: '../node_modules/protractor/selenium/selenium-server-standalone-2.37.0.jar',
   // The port to start the selenium server on, or null if the server should
   // find its own unused port.
   seleniumPort: null,
@@ -19,7 +19,7 @@ exports.config = {
   // find chromedriver. This will be passed to the selenium jar as
   // the system property webdriver.chrome.driver. If null, selenium will
   // attempt to find chromedriver using PATH.
-  chromeDriver: './selenium/chromedriver',
+  chromeDriver: '../node_modules/protractor/selenium/chromedriver',
   // Additional command line options to pass to selenium. For example,
   // if you need to change the browser timeout, use
   // seleniumArgs: ['-browserTimeout=60'],

```

**Pull request merged**
